name: Build
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  workflow_dispatch:
    # manual trigger

jobs:
  Vitepress_build:
    runs-on: ubuntu-latest
    container: locietta/loia-dev-base:latest
    name: Vitepress Deploy
    steps:
    - uses: actions/checkout@v2
    - name: Setup and build
      shell: bash
      run: |
        pnpm i
        pnpm build
        cd .vitepress/dist
        touch .nojekyll
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        echo '${{ secrets.CUSTOM_DOMAIN }}' > CNAME
        git init
        git add -A
        git commit -m autobuild
        git push -f https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git master:gh-pages