name: Build
on:
  push:
    branches:
      - main
      - demo
    tags-ignore:
      - '**'
  workflow_dispatch:
    # manual trigger

jobs:
  Vitepress_build:
    runs-on: ubuntu-latest
    container: locietta/loia-dev-base:latest
    name: Vitepress Deploy
    steps:
    - uses: actions/checkout@main
    - name: Setup and build
      shell: bash
      run: |
        pnpm i
        pnpm build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: .vitepress/dist
        cname: ${{ secrets.CUSTOM_DOMAIN }}